### ISSUE TITLE
Application crashes after upgrading from 2.1.0 to 2.1.1

### ISSUE THREAD

**Issue by JestemStefan** [dabapps/django-log-request-id#80]
We started getting an error during application startup. Might be related to celery process, but hard to tell exactly.

Error trace

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/asgiref/local.py", line 19, in **getattr**
    return storage_object[key]
           ~~~~~~~~~~~~~~^^^^^
KeyError: 'request_id'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".........../wsgi.py", line 34, in application
    uwsgi.set_logvar("request_id". local.request_id)

  File "/usr/local/lib/python3.13/site-packages/asgiref/local.py", line 21, in **getattr**
    raise AttributeError(f"{self!r} object has no attribute {key!r}")
AttributeError: <asgiref.local._CVar object at 0x7f8f5fae8ad0> object has no attribute 'request_id'
```

`local` is imported from `log_request_id`

It works fine in version 2.1.0 and earlier

We use Django 5.2 and Python 3.13

**Comment by JestemStefan** [comment]
Error is raised during health check call so it seems to have nothing to do with celery as I thought earlier

**Comment by j4mie** [comment]
Hi @JestemStefan thanks for the issue and sorry for the bug. Unfortunately I can't seem to reproduce this locally - upgrading to 2.1.1 causes no issues on our projects. Can you give me any more details? What does your "health check call" do? Can you give me any more of the traceback (even if parts are redacted?)

**Comment by JestemStefan** [comment]
This is basically entire error trace. 

There is one more line stating

[11/Mar/2026:16:42:16 +0000] '-' app=- req=- [{26 vars in 380 bytes} GET /api/health_check/ => generated 0 bytes in 23 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0) [wid: 8|pid: 98|rss: 191M]

And that's it.


Health check is very simple. It's a middleware and it's right after RequestIDMiddleware 
```
MIDDLEWARE = [
    "log_request_id.middleware.RequestIDMiddleware",
    "common.middleware.HealthCheckMiddleware",
    ...
]
```

It just returns 200 OK
```
class HealthCheckMiddleware:
    """
    Middleware to handle health check requests.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        if request.path == "/api/health_check/":
            return HttpResponse()
        return self.get_response(request)
```

**Comment by j4mie** [comment]
I think I can see the problem now. #75 refactored the `RequestIDMiddleware` and we now clear the `request_id` from the `local` on the way out of the middleware unconditionally. Previously we only cleared it if `LOG_REQUESTS` was set to `True` in the settings, which maybe not quite a "bug" but was definitely a slightly weird behaviour. I assume `LOG_REQUESTS` is set to `False` for your application? (`False` is the default).

I do have a patch in mind that might fix this, but first can you share a bit more of your `wsgi.py`? I need to see exactly where you're calling `uwsgi.set_logvar("request_id". local.request_id)`

**Comment by JestemStefan** [comment]
Yes. I see that in our app `LOG_REQUESTS` is not set so this conditions defaults to `False`

```
        if not getattr(settings, LOG_REQUESTS_SETTING, False):
            return response
```
wsgi setup is nothing fancy

```
import uwsgi
from django.core.wsgi import get_wsgi_application

django_application = get_wsgi_application()

def application(environ, start_response):
    try:
        return django_application(environ, start_response)
    finally:
        uwsgi.set_logvar("request_id",  local.request_id)
```

**Comment by j4mie** [comment]
@JestemStefan I've just released version 2.1.2 which hopefully fixes this. Can you give it a try and let me know?

**Comment by JestemStefan** [comment]
I can say it's working in the sense that app is starting, but I need some time to confirm that everything is working fine.

I will confirm that tomorrow after gathering more logs. Is that ok?

**Comment by JestemStefan** [comment]
Everything seems to be working fine know.

Thank you!

**Comment by j4mie** [comment]
Brilliant, thanks @JestemStefan!
